### PR TITLE
Implementation of "160. Feature Launcher Service Specification" ( issues 13, 14, 33, 34, 35, 36 )

### PR DESCRIPTION
**Pull request by ideas-into-software**
- Owning features (c.d.) - Support for externally installed bundles

 - Feature Extension Handlers (c.d.) - Bundle Start Levels Feature Extension Handler ( built-in )

 - Feature Extension Handlers (c.d.) - Framework Launching Properties Feature Extension Handler ( built-in )

 - Feature Extension Handlers (c.d.) - Feature validation

 - Feature Decorators (c.d.) - Feature validation

 - Overriding Feature variables

 - Setting the bundle start levels

 - Temporary workaround for Felix OSGi framework bug

 - Refactoring / fixes / improvements

### CODE REVIEW

**Comment by ideas-into-software** [comment]
https://github.com/kentyou/feature-launcher-prototype/issues/13
https://github.com/kentyou/feature-launcher-prototype/issues/14
https://github.com/kentyou/feature-launcher-prototype/issues/33
https://github.com/kentyou/feature-launcher-prototype/issues/34
https://github.com/kentyou/feature-launcher-prototype/issues/35
https://github.com/kentyou/feature-launcher-prototype/issues/36

**Comment by ideas-into-software** [comment]
### ISSUES

For two out of several issues encountered I created separate entries in issue tracker, i.e.: 

 - https://github.com/kentyou/feature-launcher-prototype/issues/36
   
 - https://github.com/kentyou/feature-launcher-prototype/issues/38

For Felix OSGi Framework bug (#36), I applied temporary workaround until it is fixed - please see https://github.com/kentyou/feature-launcher-prototype/issues/36 for details.

### QUESTIONS

1. Regarding section 159.8 ("Framework Launching Properties"), which mentions (...) "_The Launcher must be able to satisfy the specified properties. If it cannot ensure that these are present in the running Framework the launcher must fail_" (...) - which I run into when working on working on `FRAMEWORK_LAUNCHING_PROPERTIES` `FeatureExtensionHandler`:

 a) Since there seems to be no way to check whether specific framework launch properties are supported by given OSGi framework implementation and framework launching does not fail if properties other that those defined on `org.osgi.framework.Constants` and `org.apache.felix.framework.util.FelixConstants` are specified, is that requirement valid ?
 
 b) Shouldn't there be a way to check whether specific framework launch properties are supported using OSGi Core implementation itself ? Currently, framework launch properties are defined in `org.osgi.framework.Constants` as well as in `org.apache.felix.framework.util.FelixConstants` ( for Felix OSGi Framework implementation ) - but those classes mix framework launch properties with other constants and do not name fields which declare them consistently, so creating util class like `com.kentyou.featurelauncher.impl.util.FrameworkEventUtil` / `com.kentyou.featurelauncher.impl.util.BundleEventUtil`, which reads those declared fields and provides additional methods ( e.g. to look up if given property is supported ) would be problematic.

2. With `FRAMEWORK_LAUNCHING_PROPERTIES` `FeatureExtensionHandler` now implemented  ( `com.kentyou.featurelauncher.impl.decorator.FrameworkLaunchingPropertiesFeatureExtensionHandlerImpl` ), framework launching properties can now be specified via `com.kentyou.featurelauncher.impl.FeatureLauncherImpl.LaunchBuilderImpl.withFrameworkProperties(Map<String, String>)` as well as `FRAMEWORK_LAUNCHING_PROPERTIES` `FeatureExtension` - should those framework properties be merged or only those specified via launcher / only those specified in feature extension should be used ? See `com.kentyou.featurelauncher.impl.FeatureLauncherImpl.LaunchBuilderImpl.getFrameworkProperties() for details how this is implemented currently.

### OTHER

 - Since I did not find constants for properties supported by `BUNDLE_START_LEVELS` `FeatureExtension` in `FeatureLauncherConstants` ( where e.g. `BUNDLE_START_LEVELS` is defined ), I added them `FeatureDecorationConstants` ( `BUNDLE_START_LEVELS_DEFAULT`, `BUNDLE_START_LEVELS_MINIMUM` );

**Comment by timothyjward** [comment]
Thank you for the contribution - in future please try to address features in smaller pull requests as they're easier to review, and they are simpler for people to understand when browsing the history

> a) Since there seems to be no way to check whether specific framework launch properties are supported by given OSGi framework implementation and framework launching does not fail if properties other that those defined on `org.osgi.framework.Constants` and `org.apache.felix.framework.util.FelixConstants` are specified, is that requirement valid ?

This simply means that the implementation must check that the framework launch properties have been set, using `BundleContext.getProperty()` and have the correct values.

> With FRAMEWORK_LAUNCHING_PROPERTIES FeatureExtensionHandler now implemented ( com.kentyou.featurelauncher.impl.decorator.FrameworkLaunchingPropertiesFeatureExtensionHandlerImpl ), framework launching properties can now be specified via com.kentyou.featurelauncher.impl.FeatureLauncherImpl.LaunchBuilderImpl.withFrameworkProperties(Map<String, String>) as well as FRAMEWORK_LAUNCHING_PROPERTIES FeatureExtension - should those framework properties be merged or only those specified via launcher / only those specified in feature extension should be used ? 

They should be merged, and the builder value always overrides the feature document.

**Comment by ideas-into-software** [comment]
@timothyjward 

This is just to remind that since you merged this PR, you can close the following issues: 

 - https://github.com/kentyou/feature-launcher-prototype/issues/13
 
 - https://github.com/kentyou/feature-launcher-prototype/issues/14
 
 - https://github.com/kentyou/feature-launcher-prototype/issues/33
 
 - https://github.com/kentyou/feature-launcher-prototype/issues/34
 
 - https://github.com/kentyou/feature-launcher-prototype/issues/35
 

Regarding https://github.com/kentyou/feature-launcher-prototype/issues/36 - this is to document bug I encountered and temporary solution I applied; until underlying cause of this problem is solved, this particular issue should remain opened, IMHO.

**Pull request merged**
