### PR TITLE
Implementation of "160. Feature Launcher Service Specification" ( issues 15 16 )

### PR DESCRIPTION
**Pull request by ideas-into-software**
- Feature Decorators
 
 - Feature Extension Handlers
 
 - Refactoring / fixes / improvements

### CODE REVIEW

**Comment by ideas-into-software** [comment]
https://github.com/kentyou/feature-launcher-prototype/issues/15
https://github.com/kentyou/feature-launcher-prototype/issues/16

**Comment by ideas-into-software** [comment]
Merging this will merge changes contained in https://github.com/kentyou/feature-launcher-prototype/pull/29 and https://github.com/kentyou/feature-launcher-prototype/pull/30

**Comment by ideas-into-software** [comment]
When you review this PR, you will notice that so called built-in feature extension handlers - i.e. extension handlers which specification says must be supported by each implementation - are not fully implemented.

There is a problem with how the Feature Launcher API currently expects feature extensions ( `org.osgi.service.feature.FeatureExtension` to be processed via feature extension handlers `org.osgi.service.featurelauncher.decorator.FeatureExtensionHandler` - at least for the built-in feature extensions ( i.e.  `org.osgi.service.featurelauncher.FeatureLauncherConstants.LAUNCH_FRAMEWORK`, `org.osgi.service.featurelauncher.FeatureLauncherConstants.FRAMEWORK_LAUNCHING_PROPERTIES` and `org.osgi.service.featurelauncher.FeatureLauncherConstants.BUNDLE_START_LEVELS` ), information contained in those extensions is required at different stages of launching / installing feature and cannot be passed back to calling code in feature `org.osgi.service.feature.Feature` object, which is the only object returned from the only method `org.osgi.service.featurelauncher.decorator.FeatureExtensionHandler.handle(Feature, FeatureExtension, FeatureExtensionHandlerBuilder, DecoratorBuilderFactory)` defined on feature extension handler.

1. In the case of `org.osgi.service.featurelauncher.FeatureLauncherConstants.LAUNCH_FRAMEWORK` feature extension, information contained in that extension is required when locating framework implementation, as defined in section 160.4.3.2. To enable passing back required information, i.e. instance of `org.osgi.framework.launch.FrameworkFactory`, to where it is needed during the process of launching feature, necessitated defining additional interface (` com.kentyou.featurelauncher.impl.decorator.LaunchFrameworkFeatureExtensionHandler` and calling that additional method defined on that interface when locating framework implementation from ( `com.kentyou.featurelauncher.impl.FrameworkFactoryLocator.locateFrameworkFactory(Feature, List<ArtifactRepository>)` ) method.

2. In the case of `org.osgi.service.featurelauncher.FeatureLauncherConstants.FRAMEWORK_LAUNCHING_PROPERTIES` feature extension, information contained in that extension is required when creating framework instance via `org.osgi.framework.launch.FrameworkFactory.newFramework(Map<String, String>)` method - it cannot be passed back in "processed" feature (`org.osgi.service.feature.Feature`) object as it is currently defined by separate OSGi specification ( 159 ), and even if it were, the calling code would have to check again and extract this information so these user-defined framework properties can be used when creating new instance of framework.

As a side note, this extension appears obsolete when processing extensions in `org.osgi.service.featurelauncher.runtime.FeatureRuntime` implementation and is only relevant when processing extensions in `org.osgi.service.featurelauncher.FeatureLauncher` implementation.

3. In the case of `org.osgi.service.featurelauncher.FeatureLauncherConstants.BUNDLE_START_LEVELS` feature extension, at least some of the information contained in that extension, i.e. `org.osgi.framework.startlevel` framework launch property, is required when creating framework instance via `org.osgi.framework.launch.FrameworkFactory.newFramework(Map<String, String>)` method, similar to `org.osgi.service.featurelauncher.FeatureLauncherConstants.FRAMEWORK_LAUNCHING_PROPERTIES` feature extension ( see item 2 above ).

In addition, similarly to `org.osgi.service.featurelauncher.FeatureLauncherConstants.FRAMEWORK_LAUNCHING_PROPERTIES` extension ( see item 2 above ), it is only relevant to `org.osgi.service.featurelauncher.FeatureLauncher` implementation.
 
As can be seen, at least for these built-in extensions, since required information cannot be passed back to calling code and is required at different stages of processing, these extensions cannot be processed via `com.kentyou.featurelauncher.impl.util.FeatureExtensionUtil.executeFeatureExtensionHandlers(Feature, Map<String, FeatureExtensionHandler>)`.

One possible solution would be to introduce additional parameter to `org.osgi.service.featurelauncher.decorator.FeatureExtensionHandler.handle(Feature, FeatureExtension, FeatureExtensionHandlerBuilder, DecoratorBuilderFactory)` method, which "collects" such information ( e.g. instance of  `org.osgi.framework.launch.FrameworkFactory`, framework launching properties, etc. ) which can then be utilized by calling code when it's actually needed.

Therefore, until this issue is resolved at API level, implementations of these are essentially no-op: 

 - `com.kentyou.featurelauncher.impl.decorator.LaunchFrameworkFeatureExtensionHandlerImpl.handle(Feature, FeatureExtension, FeatureExtensionHandlerBuilder, DecoratorBuilderFactory)`

 - `com.kentyou.featurelauncher.impl.decorator.FrameworkLaunchingPropertiesFeatureExtensionHandlerImpl.handle(Feature, FeatureExtension, FeatureExtensionHandlerBuilder, DecoratorBuilderFactory)`

 - `com.kentyou.featurelauncher.impl.decorator.BundleStartLevelsFeatureExtensionHandlerImpl.handle(Feature, FeatureExtension, FeatureExtensionHandlerBuilder, DecoratorBuilderFactory)`

.. while both `FeatureLauncher` and `FeatureRuntime` implementations have the necessary code for processing both feature decorators and feature extension handles "plugged in" - see calls to `executeFeatureDecorators` and `executeFeatureExtensionHandlers` methods.


### Questions

 1. Would solution proposed to above mentioned problem with built-in feature extension handlers be acceptable to you or what other solution do you propose to resolve that problem ? 
 
 2. Specification also states that `AbandonOperationException` should be thrown if feature (`org.osgi.service.feature.Feature`) object returned by calls to `org.osgi.service.featurelauncher.decorator.FeatureDecorator.decorate(Feature, FeatureDecoratorBuilder, DecoratorBuilderFactory)` or `org.osgi.service.featurelauncher.decorator.FeatureExtensionHandler.handle(Feature, FeatureExtension, FeatureExtensionHandlerBuilder, DecoratorBuilderFactory)` is (**A**) not the original feature object or (**B**) feature constructed by `org.osgi.service.featurelauncher.decorator.BaseFeatureDecorationBuilder.build()`, but how can this be checked by calling code in (B) case if calling code does not know what is done inside those methods (`decorate`, `handle`) and only `ID` is preserved ( aside from its classifier part ) ? 
 
 3. In section 160.4.3.1 ("Feature Decoration") specification also states the following: 
 
> (...) If no Feature Extension Handler can be found, and the extension name is one of:
>  - LAUNCH_FRAMEWORK
>  - FRAMEWORK_LAUNCHING_PROPERTIES
>  - BUNDLE_START_LEVELS
> then create an empty Feature Extension Handler which may validate the FeatureExtension.Type of the extension and must return the original feature. (...)

 .. but (**A**) why would those Feature Extension Handlers not be found if they are required to be supported, as stated in other sections by said specification ( 160.4.3.1, 160.4.2.1, 160.3.2, and other, where `LAUNCH_FRAMEWORK`, `FRAMEWORK_LAUNCHING_PROPERTIES` and `BUNDLE_START_LEVELS` feature extensions are mentioned), and (**B**) what's the purpose of creating empty Feature Extension Handler if they must be supported ?

 4. Is there a need for any "built-in" `org.osgi.service.featurelauncher.decorator.FeatureDecorator` implementations ( i.e. as part of Feature Launcher implementation, like there is for built-in feature extension handlers ) or is this interface only to be implemented as needed by those who wish to extend processing done as part of this "Feature Launcher" implementation, and no built-in implementations are required?

 5. Which should be used for "feature extension name": `feature.getExtensions().getKey()` or `featureExtension.getName()`, and are both needed ? Both are available, but only one can be used.
 
 6. Should original feature be stored on `com.kentyou.featurelauncher.impl.FeatureLauncherImpl.LaunchBuilderImpl` and `com.kentyou.featurelauncher.impl.runtime.FeatureRuntimeImpl.AbstractOperationBuilderImpl<T>` ?

**Review by timothyjward — APPROVED** [review]

**Comment by timothyjward** [comment]
> ### Questions
> 1. Would solution proposed to above mentioned problem with built-in feature extension handlers be acceptable to you or what other solution do you propose to resolve that problem ?

We seem to have a difference of opinion as to what needs to be possible from within the Feature Extension Handler, as opposed to what the implementation of the Feature Launcher needs to be able to achieve. Part of the reason that the "built-in" extensions are special and must be provided by the implementation of the Feature Launcher is expressly because they require additional handling that can only be performed by the Feature Launcher. In all of these cases I would expect there to be additional methods on the implementation of `FeatureExtensionHandler` that the implementation could use, e.g. this incomplete example:

```
BundleStartLevelsFeatureExtensionHandlerImpl implements FeatureExtensionHandler {

private Integer defaultBundleStartLevel;

private Integer minimumFrameworkStartLevel;

public Feature handle(Feature f, FeatureExtension fe, FeatureExtensionHandlerBuilder feb, DecoratorBuilderFactory dbf) {

    if(!isValid(fe)) {
        throw new AbandonOperationException("The start level configuration for feature " + f.getId() + " is invalid");
    }

    Map<String, Integer> map = readJSON(fe.getJSON());

    defaultBundleStartLevel = map.get("defaultStartLevel");
    minimumFrameworkStartLevel = map.get("minimumStartLevel");

    return f;
}

Integer getDefaultBundleStartLevel() {
    return defaultBundleStartLevel;
}

Integer getMinimumFrameworkStartLevel() {
    return minimumFrameworkStartLevel;
}

```

The Feature Launcher/Runtime can then use these implementation methods to get the information that it needs to continue.

> 2. Specification also states that `AbandonOperationException` should be thrown if feature (`org.osgi.service.feature.Feature`) object returned by calls to `org.osgi.service.featurelauncher.decorator.FeatureDecorator.decorate(Feature, FeatureDecoratorBuilder, DecoratorBuilderFactory)` or `org.osgi.service.featurelauncher.decorator.FeatureExtensionHandler.handle(Feature, FeatureExtension, FeatureExtensionHandlerBuilder, DecoratorBuilderFactory)` is (**A**) not the original feature object or (**B**) feature constructed by `org.osgi.service.featurelauncher.decorator.BaseFeatureDecorationBuilder.build()`, but how can this be checked by calling code in (B) case if calling code does not know what is done inside those methods (`decorate`, `handle`) and only `ID` is preserved ( aside from its classifier part ) ?

The calling code has full control of what is passed in. There could easily be a method on `AbstractBaseFeatureDecorationBuilder` such as:

```
void enforceValidFeature(Feature f) {
    if(f == originalFeature || f == returnedFeature) {
        throw new AbandonOperationException("The feature returned by the decorator was not the original, or one created by the supplied builder");
    }
}
```

There are other similar approaches, but fundamentally the implementation can tell if the feature object is the original, or if it came from the builder.

> 3. In section 160.4.3.1 ("Feature Decoration") specification also states the following:
> 
> > (...) If no Feature Extension Handler can be found, and the extension name is one of:
> > 
> > * LAUNCH_FRAMEWORK
> > * FRAMEWORK_LAUNCHING_PROPERTIES
> > * BUNDLE_START_LEVELS
> >   then create an empty Feature Extension Handler which may validate the FeatureExtension.Type of the extension and must return the original feature. (...)
> 
> .. but (**A**) why would those Feature Extension Handlers not be found if they are required to be supported, as stated in other sections by said specification ( 160.4.3.1, 160.4.2.1, 160.3.2, and other, where `LAUNCH_FRAMEWORK`, `FRAMEWORK_LAUNCHING_PROPERTIES` and `BUNDLE_START_LEVELS` feature extensions are mentioned), and (**B**) what's the purpose of creating empty Feature Extension Handler if they must be supported ?

You're right, this is leftover text and it should be removed.

> 
> 4. Is there a need for any "built-in" `org.osgi.service.featurelauncher.decorator.FeatureDecorator` implementations ( i.e. as part of Feature Launcher implementation, like there is for built-in feature extension handlers ) or is this interface only to be implemented as needed by those who wish to extend processing done as part of this "Feature Launcher" implementation, and no built-in implementations are required?

I don't think that there are any built-ins required.

> 5. Which should be used for "feature extension name": `feature.getExtensions().getKey()` or `featureExtension.getName()`, and are both needed ? Both are available, but only one can be used.

The key in the `Map` for each entry returned by `feature.getExtensions()` is identical to the `String` returned by `featureExtension.getName()`. You can therefore use either as they are guaranteed to work.

> 6. Should original feature be stored on `com.kentyou.featurelauncher.impl.FeatureLauncherImpl.LaunchBuilderImpl` and `com.kentyou.featurelauncher.impl.runtime.FeatureRuntimeImpl.AbstractOperationBuilderImpl<T>` ?

It can be stored wherever makes the most sense. Once the operations have been completed they should become totally useless (i.e. throw `IllegalStateException`) and should be discarded by the caller, but the implementation can do what it likes.

**Pull request merged**
